name = "basecart-storefront"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXT_PUBLIC_API_URL = "https://api.basecart.app"
NEXT_PUBLIC_STOREFRONT_DOMAIN = "basecart.app"
